// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceParkAPI.Db_Context;

namespace SpaceParkAPI.Migrations
{
    [DbContext(typeof(SpaceParkContext))]
    partial class SpaceParkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("SpaceParkAPI.Models.ParkingLotModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("ParkingLots");
                });

            modelBuilder.Entity("SpaceParkAPI.Models.ParkingSpaceModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("ParkingLotID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SpaceShipID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ParkingLotID");

                    b.HasIndex("SpaceShipID");

                    b.ToTable("ParkingSpaces");
                });

            modelBuilder.Entity("SpaceParkAPI.Models.PersonModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PersonModels");
                });

            modelBuilder.Entity("SpaceParkAPI.Models.SpaceshipModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("PersonID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("SpaceshipModels");
                });

            modelBuilder.Entity("SpaceParkAPI.Models.ParkingSpaceModel", b =>
                {
                    b.HasOne("SpaceParkAPI.Models.ParkingLotModel", "ParkingLot")
                        .WithMany("ParkingSpaces")
                        .HasForeignKey("ParkingLotID");

                    b.HasOne("SpaceParkAPI.Models.SpaceshipModel", "SpaceShip")
                        .WithMany()
                        .HasForeignKey("SpaceShipID");

                    b.Navigation("ParkingLot");

                    b.Navigation("SpaceShip");
                });

            modelBuilder.Entity("SpaceParkAPI.Models.SpaceshipModel", b =>
                {
                    b.HasOne("SpaceParkAPI.Models.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SpaceParkAPI.Models.ParkingLotModel", b =>
                {
                    b.Navigation("ParkingSpaces");
                });
#pragma warning restore 612, 618
        }
    }
}
